### ISSUE TITLE
Repair broken folder on de.solidcommunity.net

### ISSUE THREAD

**Issue by angelo-v** [solid/solidcommunity.net#33]
Requesting https://de.solidcommunity.net/treffen/ leads to a 500 Error:

```UnhandledPromiseRejectionWarning: SFCFetchError: SFCFetchError 500 https://de.solidcommunity.net/treffen/ - An internal server error occured```

Something is wrong with this folder, proably ACL related. Please someone with file system access take a look. If there is no obvious repair please delete the folder and I will upload a backup.

**Comment by angelo-v** [comment]
The web page says `Can't parse container`

**Comment by bourgeoa** [comment]
@angelo-v 
This is the first time I found this error to repair.
- There is no problem to access treffen/2021/ or treffen/2022
- Your .acl is ok
- But your .meta is wrong, it as been created with a text `null` content. This cannot be parsed by text/turtle.
  I copy it to .meta.txt deleted the old .meta and re-created .meta with no content using soid-ide to have all controls on.

to do the above I added myself (a non permanent webId) to your .acl, and added https://de.solid.community.net to my trusted app : `please do remove me`. I did not remove myself so you know exactly what has been done.

**Comment by angelo-v** [comment]
Ah thank you so much. Can you also delete https://de.solidcommunity.net/meetings/, this is an old one with the same error, but not needed anymore. I will investigate the root cause

**Comment by bourgeoa** [comment]
I moved meetings/.meta to meetings/.meta.txt as you can see the problem was the same, but also on meetings/2020/.meta, moved also
I prefer you check and delete yourself. The previous was only on first level.
I suppose this arrive with folder creation using PUT folder/.meta with a meta content in lieu of POST with slug

NSS on https://solidcommunity.net:8443 can create folder with PUT folder/ I shall update the test server tomorrow to include more improvements. I'm slowly making the server solid/test-suite compliant. 

Then if it's ok please close this issue.

**Comment by angelo-v** [comment]
It might have been caused by an old version of solid-file-client, I will upgrade and take a careful look how it behaves now. Thanks again!

**Comment by bourgeoa** [comment]
@angelo-v Can you open issues to : 
- solid-file-client client that should not add null text
- and to NSS that should check that .meta is a valid RDF

**Comment by angelo-v** [comment]
I think the latest version of solid-file-client is fine, I did not find any `null`-containing meta files any more. For NSS I created the above issue.
