### ISSUE TITLE
.acl errors and lose access

### ISSUE THREAD

**Issue by scenaristeur** [solid/solidcommunity.net#40]
Sorry but it seems that i've lost access to some of my PODs folders trying to setting some inbox-like authorizations https://github.com/jeff-zucker/solid-file-client/issues/189 

i've lost access to https://spoggy-test9.solidcommunity.net/inbox/annonces/
and to /annonces, /annonces2, /annonces3, /annonces4 folders in 
https://spoggy-test2.solidcommunity.net/inbox/

annonces5 is ok for the moment

Could an admin fix this issues

thxs

**Comment by bourgeoa** [comment]
@scenaristeur 
> i've lost access to https://spoggy-test9.solidcommunity.net/inbox/annonces/

I'm surprised because I have access with my webId to the folder but not to the contents : this is what you specified with accessTo for everyconnectedAgent with ReadWrite. And yourself with  ReadWriteControl.

You should add  : 
`:ReadWriteControl acl:default target:;` this will give you `acl:accessTo` to the folder and with` default` to all contents
to do that keeping the actual .acl structure
- goto `https://spoggy-test9.solidcommunity.net/inbox/annonces/.acl` and use the edit pane (no security on acl only on turtle)
- or use solid-ide where you can edit the .acl (there the .acl is checked for validity)

**Comment by bourgeoa** [comment]
You should be able to resolve spoggy-test2 using the same process on `https://spoggy-test2.solidcommunity.net/inbox/` first
I also added myself to validate that you should have access.

**Comment by bourgeoa** [comment]
> or use solid-ide where you can edit the .acl (with solid-ide the .acl is checked for validity) (not tested, may be not working if no acl:default !!!!)

not working because no acl:default : this is because the app is looking at folder/resources.acl.

**Comment by scenaristeur** [comment]
thxs ;-)
